# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - bash ./docs/setup_environment.sh  # install EPANET2 in the environment

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py

# Set Python requirements
python:
  install:
    - requirements: requirements-dev.txt
    - method: setuptools
      path: .

formats: all
